"use client";
import { useEffect, useState, type FormEvent } from "react";
import { api, type AuthResponse, type AccountInvitation } from "@/lib/api";
import { accountToken, parseClaimLink } from "@/lib/account";
import "./account.css";
const CLAIMED = "moc.account.claimed-links";
const readKeys = (): Record<string, string> => { try { return JSON.parse(sessionStorage.getItem(CLAIMED) ?? "{}"); } catch { return {}; } };
export function AccountClient() {
  const [register, setRegister] = useState(false), [email, setEmail] = useState(""), [password, setPassword] = useState(""), [link, setLink] = useState(""), [items, setItems] = useState<AccountInvitation[]>([]), [keys, setKeys] = useState<Record<string, string>>({}), [error, setError] = useState(""), [token, setToken] = useState("");
  const refresh = async (t: string) => { setItems(await api.listAccountInvitations(t)); setKeys(readKeys()); };
  useEffect(() => { const t = accountToken.get(); setToken(t); if (t) refresh(t).catch(() => { accountToken.clear(); setToken(""); }); }, []);
  async function submit(e: FormEvent) { e.preventDefault(); setError(""); try { const r: AuthResponse = register ? await api.register(email, password) : await api.login(email, password); accountToken.set(r.accessToken); setToken(r.accessToken); await refresh(r.accessToken); } catch (e) { setError(e instanceof Error ? e.message : "Chưa thực hiện được"); } }
  async function claim(e: FormEvent) { e.preventDefault(); setError(""); const parsed = parseClaimLink(link, window.location.origin); if (!parsed) { setError("Link chỉnh sửa không hợp lệ."); return; } try { await api.claimInvitation(token, parsed.id, parsed.key); const next = { ...readKeys(), [parsed.id]: parsed.key }; sessionStorage.setItem(CLAIMED, JSON.stringify(next)); setLink(""); await refresh(token); } catch (e) { setError(e instanceof Error ? e.message : "Chưa nhận được thiệp"); } }
  if (token) return <main className="account-page"><section className="account-card"><p className="eyebrow">MỘC Wedding</p><h1>Thiệp của <em>bạn.</em></h1><button className="button-ghost account-logout" type="button" onClick={() => { accountToken.clear(); setToken(""); }}>Đăng xuất</button><form className="account-claim" onSubmit={claim}><label>Nhận thiệp cũ bằng link chỉnh sửa<input className="input" value={link} onChange={e => setLink(e.target.value)} placeholder="https://…/studio/…#k=…" required /></label><button className="button-primary">Nhận thiệp</button></form>{error && <p className="form-error" role="alert">{error}</p>}<ul className="account-list">{items.map(i => <li key={i.id}><a className="account-invitation" href={keys[i.id] ? `/studio/${i.id}#k=${encodeURIComponent(keys[i.id])}` : `/studio/${i.id}`}><strong>{i.slug}</strong><small>{i.published ? "Đã xuất bản" : "Bản nháp"}</small></a></li>)}</ul></section></main>;
  return <main className="account-page"><section className="account-card"><p className="eyebrow">MỘC Wedding</p><h1>{register ? "Tạo tài khoản" : "Đăng nhập"}</h1><p className="lede">Lưu và quản lý các thiệp cưới của bạn trên mọi thiết bị.</p><form className="account-form" onSubmit={submit}><label>Email<input className="input" type="email" value={email} onChange={e => setEmail(e.target.value)} required /></label><label>Mật khẩu<input className="input" type="password" value={password} onChange={e => setPassword(e.target.value)} minLength={8} required /></label><button className="button-primary">{register ? "Đăng ký" : "Đăng nhập"}</button></form>{error && <p className="form-error" role="alert">{error}</p>}<button className="link-quiet account-switch" type="button" onClick={() => setRegister(!register)}>{register ? "Đã có tài khoản? Đăng nhập" : "Chưa có tài khoản? Tạo tài khoản"}</button></section></main>;
}
